### ISSUE TITLE
[Class-System] Sprung: Sprung verursacht Fallschaden

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#10]
Found
Sprung: Sprung verursacht Fallschaden

STR
- Wähle Waldläufer und schalte Sprung frei
- Benutze den Skill

-> Nutzer erhält Fallschaden

**Comment by TimK1998** [comment]
Fixed. But the player still gets fall damage if he hits a block while in air. This is not fixable.

**Comment by TimK1998** [comment]
Sollte funktionieren, hatte es zumindest bei mir immer, aber bitte nochmal prüfen @Timkoe
