### ISSUE TITLE
[Guild-System] Gildengebietsborders sind inkorrekt

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#113]
Found
- An einer Seite wird Gildengrenzgebiet von Core gebiet überlappt
- Gildengrenzgebiete sind an bordern nicht konsistent

- Gebiete verkleinern

**Comment by Kyraja** [comment]
Bitte genauer definieren! Welche Seite? Und was heißt nicht konsistent? Bitte größe der neuen Gebiete definieren.

**Comment by Timkoe** [comment]
100 statt 150 Core gebiet, Gebietsgrenzen funktionieren
