### ISSUE TITLE
[Entity-System] Spieler werden zufällig unsichtbar, vorallem bei Respawns

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#12]
Found
Spieler werden zufällig unsichtbar, vorallem bei Respawns

Reproduction:
Unbekannt mögliche Ursache bei Spawns / Respawns
Potenzieller Zusammenhang mit Skills

Result
Spieler werden zufällig unsichtbar, vorallem bei Respawns

**Comment by TimK1998** [comment]
Should be fixed after switch to Spigot.
