### ISSUE TITLE
[Class-System] Task: Waldläufer muss mehr DMG auf Distanz verursachen, aber weniger auf Nähe

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#120]
Bow Damage auf Nähe reduzieren,
Bow Damage auf entfernung erhöhen

**Comment by TimK1998** [comment]
Voller Schaden ist jetzt ab 15 Blöcke. Schaden selbst musst du umstellen.

**Comment by Timkoe** [comment]
Base Dmg auf 140. Müssen testen ob Bowspam jetzt dennoch zu stark wird.
