### ISSUE TITLE
[Combat-System] Player can hit multiple targets with sword

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#13]
Found
 Player can hit multiple targets with sword

Steps
- Get a Sword
- Attack targets close to each other

Result

 Player can hit multiple targets with sword

**Comment by TimK1998** [comment]
Planning to solve this problem next week.

**Comment by TimK1998** [comment]
The combat system is now at the state of before 1.9. The only thing that is missing ist the deactivation of the sweep attack because this is very difficult to do. (But possible)

**Comment by TimK1998** [comment]
Fixed. 

TODO: Evtl die Partikel ausschalten. Ist aber äußerst aufwendig und die Mühe wahrscheinlich nicht wert.
