### ISSUE TITLE
[UI] Task: Implement correct Guild Tag in Sidebar

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#133]
Implement correct Guild Tag & Level in Sidebar
Und korrekte Serverränge als namensfarben
Friend / enemy wird nur durch gilden tag und level angezeigt

**Comment by Kyraja** [comment]
Magst du es mir sagen wie genau es an der Sidebar aussehen soll? #Paint

**Comment by Timkoe** [comment]
![2020-02-29_13 28 11](https://user-images.githubusercontent.com/55351056/75607637-83094200-5af9-11ea-9e50-b2b9f07f5616.png)

**Comment by Timkoe** [comment]
Wenn unklar einfach im Discord fragen :D

**Comment by Timkoe** [comment]
Gildentag wird noch als feindlich angezeigt, wenn man in seiner eigenen gilde ist

**Comment by Timkoe** [comment]
Noch nicht sichtbar für andere spieler
