### ISSUE TITLE
[Class-System] Weapon Damage not working

### ISSUE THREAD

**Issue by TimK1998** [Kyraja/Lost-Kingdoms-IssueTracker#14]
The item/weapon damage for the classes is not working. It seems like you deal the normal damage amount for not listed items (10 damage).

Extra Steps:
- Get Barbar
- Equip a Diamond axe and a wooden axe
- Spawn Pig and kill with diamond (should be dead after 2 hits)
- Kill it with Wooden (needs way more than 2 hits to kill)

The weapon damage is correctly listed in Config so there must be a bug in the code.

**Comment by TimK1998** [comment]
The item names in the config must be changed to the standard of Spigot. Please close if done and it works.

**Comment by Timkoe** [comment]
Item names are changed in config. Damage / Life still does not work correctly.

**Comment by TimK1998** [comment]
It was already working. The bug was because of issue #17
