### ISSUE TITLE
[Class-System] Reset Falldamage for some Teleport Skills

### ISSUE THREAD

**Issue by TimK1998** [Kyraja/Lost-Kingdoms-IssueTracker#146]

**Comment by Torre1234** [comment]
relevante Skills:
Templer: Helfende Hand
Barbar: Aufstampfen (letzter Stand: Falldmg sobald man 1 Block tiefer als der Urspung landet)
Schurke: Dunkle Wiederkehr, Hinterhalt
Magier: Eisspiegel
