### ISSUE TITLE
{Guild-Ssystem] Gblock kann nicht vom gegner abgebaut werden im g fight

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#157]

**Comment by AioAioAio** [comment]
Gildenblock kann abgebaut werden aber für die Angreifer werden kein HP angezeigt und der 
verteidigende Gilde wird "guild.siege.blocklife.defender" angezeigt

**Comment by Timkoe** [comment]
Bitte auf message für den Angreifer anzeigen
