### ISSUE TITLE
Redstone in GFight

### ISSUE THREAD

**Issue by Ventiiix** [Kyraja/Lost-Kingdoms-IssueTracker#160]
Gegnerische Spieler sollen keine Redstone-Verstärker, Komperatorenund Tageslichtsensoren verstellen können da man sonst bei einem Angriff gegnerische Redstone Schaltungen langfristig griefen könnte.

**Comment by Timkoe** [comment]
@TimK1998 nur fixen wenn nicht zu viel Aufwand.
