### ISSUE TITLE
[Chat/Skills-Anzeige] Level 90/100 wird doppelt angezeigt.

### ISSUE THREAD

**Issue by stefanomazz** [Kyraja/Lost-Kingdoms-IssueTracker#162]
Bei der Schattenklinge wird der Level 90er und Level 100er Skill doppelt angezeigt und bei den anderen Klassen ist es nur der Level 100er Skill.

[https://i.badlion.net/XrT5WTGujAxJjN4RSJSLoh.png](url)

**Comment by Timkoe** [comment]
Level 100er muss einfach level 90er darf nicht verfügbar sein.
