### ISSUE TITLE
Tab-Format

### ISSUE THREAD

**Issue by Ventiiix** [Kyraja/Lost-Kingdoms-IssueTracker#164]
&8[&6Klassenlevel&8] &7Spielername &8[&cAVN&8]

Bei Verbündeten soll der Clantag in der Farbe &a sein und die Farbe des Spielernamens wird je nach Rang angepasst (normale Spieler &7)

**Comment by Timkoe** [comment]
https://cdn.discordapp.com/attachments/684925774331117613/685646036106215444/Alone.PNG
