### ISSUE TITLE
[Region-System]Pfeile können Armorstands,Bilder und Itemframes am Spawn zerstören

### ISSUE THREAD

**Issue by AioAioAio** [Kyraja/Lost-Kingdoms-IssueTracker#171]
Pfeile vom Bogen können Armorstands/Itemframes/Bilder am Spawn kaputt machen

**Comment by Timkoe** [comment]
&Items in  Itemframes können am spawn weggeboxt werden
wasser & lava können am spawn platziert werden
botte können am spawn geplaced werden
itemframes können platzeirt werden
felder können zerstört werden
ITEMS können aus armorstand rausgenommen / geduped werden
