### ISSUE TITLE
[Entity-System] Mobs don't give Exp after killing 3-4 

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#19]
Found
Mobs don't give Exp after killing 3-4 

Steps
- get a class (below 100)
- kill 5 mobs
- Observe Exp drops
- Kill more and observe

**Comment by TimK1998** [comment]
Could not be reproduced. Exp works as intended.

**Comment by Timkoe** [comment]
Fix verified.
