### ISSUE TITLE
[Combat-System] Bows can't cause any damage

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#24]
Found
Bows cant cause any damage

Steps
- get any class
- attack mobs with a bow

**Comment by Timkoe** [comment]
Might be cause by a wrong config entry for bows.

**Comment by Kyraja** [comment]
Besteht der Fehler noch? Ich hatte ihne gefixt. Bitte nochmal prüfen.

**Comment by Timkoe** [comment]
fix verified.
