### ISSUE TITLE
[Class-System] Jagdinstinkt: Jagdinstinkt macht nur Mobs sichtbar

### ISSUE THREAD

**Issue by Kamuuh** [Kyraja/Lost-Kingdoms-IssueTracker#33]
Found
Jagdinstinkt: Durch Jagdinstinkt werden nur Mobs sichtbar, keine anderen Spieler.

STR

 - Wähle Waldläufer und schalte Jagdinstinkt frei
 - Benutze Jagdinstinkt

 -> Man sieht Silhouetten von Friendly&Hostile Mobs. Spieler sind von dem Effekt nicht betroffen

**Comment by TimK1998** [comment]
Kann ich nicht bestätigen

**Comment by Timkoe** [comment]
@Kamuuh please retest
