### ISSUE TITLE
[Entity-System] Gift II macht zu viel Schaden

### ISSUE THREAD

**Issue by Kamuuh** [Kyraja/Lost-Kingdoms-IssueTracker#35]
Fond
Hexen werfen Gift II Tränke.

STR 

 - Hexe finden
 - Von Hexe mit Gift Trank bewerfen lassen

 -> Gift II tickt für 21 Sekunden alle 0,5 Sekunden und macht 50 Schaden pro Tick. 

Änderung: 
Den Effekt "Gift II" aus dem Spiel entfernen.

**Comment by Timkoe** [comment]
Ich würde am ehesten Gift II einfach mit Gift I gleichsetzen @TimK1998

**Comment by TimK1998** [comment]
Die Giftschäden sind schon gleich, nur tickt Gift 2 doppelt so schnell

**Comment by Timkoe** [comment]
Dann Gifttick angleichen

**Comment by TimK1998** [comment]
Geht nicht. Wenn du kein Gift 2 willst, dann mach doch keine Skills, die den Trankeffekt geben.

**Comment by TimK1998** [comment]
Wenn eine Hexe Gift II wirft, sollte daraus eine 5 sekündiger Gift 1 Trank werden. @Timkoe  Bitte testen, da ich das aktuell nicht machen kann, solange Gift mich instant killt (Schadenswerte jetzt prozentuell).

**Comment by Timkoe** [comment]
Issue sollte gefixt sein
