### ISSUE TITLE
[Class-System] Spieler Klassen-XP zurückgesetzt beim 2 relog

### ISSUE THREAD

**Issue by AioAioAio** [Kyraja/Lost-Kingdoms-IssueTracker#36]
Found
Spieler verliert erhaltene Klassen-XP nach zweiten relog

Steps to Reproduce

- Spieler logt sich das erste mal ein und wechselt Klasse

- Spieler tötet Mobs und kommt z.B. auf Level 5

- Spieler logt sich aus

- Spieler logt sich das zweite mal ein

- Spieler tötet Mobs und kommt z.B. auf Level 8

- Spieler logt sich aus

- Spieler logt sich ein

- Spieler wird auf Level 5 zurückgesetzt

Result 

Spieler wird nach jedem relog auf das Level zurückgesetzt was er beim ersten ausloggen hatte

**Comment by TimK1998** [comment]
@Kyraja Wäre schon cool, wenn du es hinbekommen würdest, wenn beim ausloggen alles korrekt gespeichert wird. Da gibt's ja schon seit ner Weile Probleme. Und meinst du, du bekommst es hin, die Datenbank auch beim Serverneustart zu saven?
