### ISSUE TITLE
[Class-System] Dunkle Wiederkehr: Dunkle Wiederkehr zieht bei der Reaktivierung erneut Mana

### ISSUE THREAD

**Issue by Kamuuh** [Kyraja/Lost-Kingdoms-IssueTracker#38]
Found 
Reaktivierung von Dunkle Wiederkehr zieht erneut 50 Mana

STR

 - Wähle Schattenklinge und schalte Dunkle Wiederkehr frei
 - Setze Dunkle Wiederkehr ein, setz es erneut ein

 -> die zweite Aktivierung kostet erneut 50 Mana

Änderung: Mana nur bei der ersten Aktivierung abziehen

**Comment by TimK1998** [comment]
Fixed
