### ISSUE TITLE
[Class-System] Improvement: Wirbelsturm: Wirbelsturm sollte Spieler stärker durch die Luft wirbeln / shiften

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#43]
Task: Wirbelsturm sollte Spieler stärker durch die Luft wirbeln / shiften

mehr details an timkoe wenden

**Comment by TimK1998** [comment]
Da Wirbelsturm eh in eine andere Art Skill umfunktioniert werden soll, close ich das jetzt mal.
