### ISSUE TITLE
[Enchantment-System] Improvement: Improvements fürs enchanting

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#48]
- Bei erfolgreichen enchant soundeffekt
- Chatmessage: Du hast dein Schwert verzaubert! (?)
- Eventuell bei enchant doppelt rechtsklicken um nicht vershentlich zu enchanten?

**Comment by TimK1998** [comment]
Bekomm ich hin
