### ISSUE TITLE
[Entity-System] Alle umgebungsschäden prozentual machen

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#51]
Alle umgebungsschäden prozentual machen

1. Timkoe im konzept ändern

2. Sieef im Plugin

**Comment by TimK1998** [comment]
TODO: @Timkoe Prozentual in Config eintragen

**Comment by TimK1998** [comment]
Bitte vorher rausfinden wie oft die jeweiligen Schadensarten ticken. Lava z.B. 2 mal pro Sekunde.
