### ISSUE TITLE
[Entity-System] Improvement: Rüstung/Schutz Iv funktioniert nicht gegen Lava und Kakteen

### ISSUE THREAD

**Issue by Ventiiix** [Kyraja/Lost-Kingdoms-IssueTracker#53]
Armor und Schutz Verzauberung ist aktuell useless gegen Lava und Kakteen

Muss noch eingefügt werden

**Comment by TimK1998** [comment]
Ich habe jetzt den Schaden von Lava, Kakteen, Explosionen und fallenden Blöcken rüstungs- und rerzauberungsabhängig gemacht. D.h. das manche von den Schadenswerten, vor allem Lava nochmal ein bisschen (ungefähr 25%) erhöht werden sollten @Timkoe .

**Comment by Timkoe** [comment]
Done
