### ISSUE TITLE
[Class-System]Hexer Feuerschoss kein Schaden 

### ISSUE THREAD

**Issue by AioAioAio** [Kyraja/Lost-Kingdoms-IssueTracker#60]
found

Hexer Feuergeschoss macht keinen Schaden mehr beim Impact sondern nur der Feuertick macht Schaden

**Comment by TimK1998** [comment]
@AioAioAio  Bitte mehr Testen wann der Schaden geht und wann nicht mehr

**Comment by AioAioAio** [comment]
kann ich nicht mehr recreaten hat sich anscheinend nach nem restart selber gefixxed
