### ISSUE TITLE
[Class-System] Task: Change sloting from skillname to slotnumber

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#62]
Task:
Change sloting from skillname to slotnumber

To make macro presets easier.

**Comment by Timkoe** [comment]
Push

**Comment by TimK1998** [comment]
Ist aktuell nicht möglich.

**Comment by Timkoe** [comment]
Statt:
/skill (skill name)
/skill (slotnummer)
