### ISSUE TITLE
[GuildSiege-System]Belagerungsturm bug beim abbauen vom Obsiblock

### ISSUE THREAD

**Issue by AioAioAio** [Kyraja/Lost-Kingdoms-IssueTracker#65]
found
Der Belagerungsturm baut sich ab wenn man nur einmal mit Linksklick auf das Obsidian haut

**Comment by TimK1998** [comment]
Liege daran, dass das noch gar nicht richtig implementiert ist.

**Comment by TimK1998** [comment]
Ist noch nicht fertig implementiert. Fällt daher zusammen mit Issue #63
