### ISSUE TITLE
[Class-System]Wutsprung Barbar in die Luft fliegen

### ISSUE THREAD

**Issue by AioAioAio** [Kyraja/Lost-Kingdoms-IssueTracker#66]
found
Wenn man Wutsprung auf ein Genger aktiviert wird der einen Block oder mehr höhen unterschied hat fliegt man sehr weit und sehr hoch weg ca. 50 Blöcke in die Luft 

Und wenn man sich auf der selben höhe befindet springt man immer 12Blöcke nach vorne egal wie weit man vom Gegner entfernt ist

**Comment by TimK1998** [comment]
Hängt zusammen mit Issue #6
