### ISSUE TITLE
(Artefakt-System) Das Artefakt kann gedroppt werden

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#69]
Found
Das Artefakt kann  nach abbau gedroppt werden
& eventuell in kisten gelegt werden

**Comment by TimK1998** [comment]
+ Random Kristalle

**Comment by Timkoe** [comment]
Kristalle: 4 Kristalle sollen an 7 random spots spawnen.

**Comment by TimK1998** [comment]
+ Hit CD
