### ISSUE TITLE
[Class-System] Task: Glaubenskraft Rework

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#82]
Task: Glaubenskraft Rework
Glaubenskraft kein Manabuff mehr sondern Skill der umliegende Ziele zu sich heran zieht,

**Comment by Timkoe** [comment]
@TimK1998 Konzept ist geändert. Glaubenskraft zieht nun feindliche Spieler im Umkreis von 10 Blocks zu sich.

**Comment by TimK1998** [comment]
Vorschlag. Spieler zieht Spieler im 10 Block Umkreis an sich heran und erschafft ein 5 Block Radius "Gefängnis", dass weder er noch die Gegner (noch Verbündete??) für x Sekunden verlassen können. @Timkoe

**Comment by TimK1998** [comment]
@Timkoe  Push

**Comment by Timkoe** [comment]
@TimK1998 stimme zu habs ins Konzept eigebaut das kann den skill etwas interessanter machen würde das gefängnis allerdings nur kurz aufrecht erhalten lassen. Außerdem müsste man das bestenfalls grafisch darstellen mit Partikeln oder Blöcken.
