### ISSUE TITLE
[Class-System] task: Hexer: Wirbelsturm rework

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#89]
Task:
Neudesign von Wirbelsturm zu DMG skill (feuer / schneesturm)

**Comment by Timkoe** [comment]
Rework fertig im Konzept, kann jetzt eingebaut werden. Modell: Axtwirbel @TimK1998

**Comment by TimK1998** [comment]
@Timkoe  Hab den Skill in Schneesturm geändert. Partikel würde ich dann machen. Man sollte sich aber überlegen, ob der Skill für Level 50 n bissl low ist, weil er sogar schwächer als Axtwirbel ist. Also entweder stärken, oder slowness hinzufügen, oder range erhöhen, oder mehreres davon.

**Comment by TimK1998** [comment]
Oder mehr Aktivierungen.

**Comment by Timkoe** [comment]
Hab den Schaden im Konzept um 10 erhöht. Grundsätzlich ist der skill allerdings auch stärker als Axtwirbel, da du doppelte Range hast.
