### ISSUE TITLE
[Class-System] Task: Schattenklinge - Implement changes:

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#91]
Task: Implement changes:

Schurke:
- Dunkle wiederkehr Zeitfenster auf 15s

- Dolchstoß umbennen zu Schattenstoss

**Comment by TimK1998** [comment]
@Timkoe 

CD von Hinterhalt ist verändert.

Schattenstoss find ich ein bisschen langweilig, da es ja schon Schattenschleier gibt, aber egal. Wenn du den Namen änderst denk dran diese Sachen alle zu ändern:

1. In der Messages_De Datei unten "skill_dolchstoss_name" und "skill_dolchstoss_description" ändern
2. Den Dateiname von Dolchstoss.lkskill ändern
3. Die Skill_Id in Dolchstoss.lkskill ändern (ä,ö,ü, Leerzeile ersetzen, alles klein geschrieben)
4.  Unter de.lostkingdoms.core.entities.classsystem.skill.classes.schattenklinge den Namen der Dolchstoss.java ändern!!! Das geht mit rechtsklick auf Dolchstoss.java -> Refactor -> Rename. Die Umbenennung ist Case Sensitive; also erster Buchstabe groß. Des weiteren Leerzeilen durch _ ersetzen und ü,ä,ö durch ue,ae,oe 

Die Dauer von Dunkle Wiederkehrt zu erhöhen finde ich krass OP. Bei 15 Sekunden kann man auf gerader Strecke 107 Blöcke weit laufen, das ist ja mal krank unfair. Wäre eher das auf 5 Sekunden runterzusetzen, denn selbst die 65 Blöcke bei 10s sind krass.

**Comment by Timkoe** [comment]
Stimme zu 10 sekunden bleiben.

**Comment by Timkoe** [comment]
Done

**Comment by Torre1234** [comment]
Schattenstoss heißt nach wie vor Dolchstoss. Mit Dolchangriff und Dolchsturz die obligatorisch und auch instant cast dmg Skills sind ist die Verwechslungsgefahr nach wie vor gegeben, finde Schattenstoss nach wie vor besser um Zusammenhang mit Schattenschleier deutlicher zu machen

**Comment by Timkoe** [comment]
Ist boch nicht gepushed.
