### ISSUE TITLE
[Class-System] Hinterhalt zu Teleport machen

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#92]
Found
Hinterhalt zu Teleport machen siehe konzept

**Comment by TimK1998** [comment]
Hinterhalt ist doch schon ein Teleport aktuell

**Comment by Timkoe** [comment]
Hinterhalt muss jetzt je nach dem umgebaut/entfernt werden, zu dem skill worauf ihr euch geeinigt habt.

**Comment by Torre1234** [comment]
Der Teleport geht aktuell nicht auf die genau Position des Gegners sondern 3 Blöcke höher, dass ist aber leider mindestens 1 Block zu hoch, sodass man Falldamage bekommt. Außerdem wurden die Werte geändert und Unischtbarkeit hinzugefügt.
