### ISSUE TITLE
[Class-System] Task: Add new lvl 5 skills

### ISSUE THREAD

**Issue by Timkoe** [Kyraja/Lost-Kingdoms-IssueTracker#94]
Task
Add new lvl 5 skills in concept

**Comment by Timkoe** [comment]
Skills sin im doc und können eingebautr werden

**Comment by TimK1998** [comment]
Habe alle Skills eingebaut.

TODO 
- in den java Dateien (im Plugin) Sounds und Effekte einbauen (wenn überhaupt nötig, bei Level 5 Skills)
- in den lkskill Dateien die Skilldaten eintragen
- in der Messages Datei die descriptions eintragen

**Comment by Timkoe** [comment]
Done.
